name: Auto Deploy GitHub Pages
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account.json
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Deploy preparation
        run: |
          echo -n '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' | base64 --decode > service-account.json

      - name: Deploy
        run: |
          yarn deploy
